services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: university_api
    environment:
      DATABASE_URL: postgresql://students:Vhtyhcn5hTCIhNWvTgnum29Sov0rY2oU@dpg-d5rgmufgi27c738sgcr0-a/university_hot0
      JWT_SECRET: supersecretkey
    ports:
      - "8080:8080"
